name: Build

on:
  - workflow_dispatch
  - push

jobs:
  build:
    name: Build, test and deploy
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Install Conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.60.2
      - name: Install Conan dependencies
        run: >
          conan install .
          -if cmake-build/dependencies/conan
          --build missing
          -s compiler="Visual Studio"
          -s compiler.version=16
          -s cppstd=20
          -s build_type=Release
      - name: Configure CMake
        run: |
          $modulePath = "${{ github.workspace }}/cmake-build/dependencies/conan"
          $normalizedModulePath = $modulePath -replace '\\', '/'
          cmake -S . -B cmake-build -D "CMAKE_MODULE_PATH=$normalizedModulePath"
      - name: Build
        run: cmake --build cmake-build --config Release
      - name: Test
        working-directory: ${{github.workspace}}/cmake-build/shmd-tests
        run: ctest
